# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [36]:
### [your code here]
import numpy as np

arr = np.array([4, 5, 3, 4, 9])
print(arr)


[4 5 3 4 9]




---



### 2. Print the NUMPY version and the configuration.


In [37]:
### [your code here]
import numpy as np

print("NumPy Version:", np.__version__)

np.show_config()


NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    n

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [38]:
### [your code here]
# we have 4 ways

import numpy as np

# 1- Create a 3D array (2, 3, 5) with random values between 0 and 1
a = np.random.random((2, 3, 5))

print(a)

# 2- takes dimensions as separate arguments instead of a tuple
a = np.random.rand(2, 3, 5)
print(a)

# 3- Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).
a = np.random.randn(2, 3, 5)
print(a)

# 4- Generates random integers between 0 and 100.
a = np.random.randint(0, 100, (2, 3, 5))
print(a)

[[[4.00924655e-01 4.00280836e-01 9.21675515e-02 6.93922743e-01
   4.89188640e-01]
  [3.85520791e-01 7.02988086e-04 2.89406386e-01 2.01367098e-01
   9.28164806e-01]
  [8.15117597e-01 1.58151712e-01 3.42241210e-01 6.13465263e-01
   1.70903596e-01]]

 [[5.51944269e-01 7.51496453e-01 2.84398996e-01 1.09307896e-01
   1.02168759e-01]
  [9.77520455e-01 1.82534816e-01 5.43225707e-01 3.30121336e-01
   6.62411427e-01]
  [8.57023708e-02 9.80207895e-02 7.74964529e-01 1.86602854e-01
   7.93994805e-01]]]
[[[0.85295426 0.39274958 0.69537321 0.13067911 0.50790146]
  [0.90603568 0.06794408 0.11690689 0.9190366  0.19075436]
  [0.55957768 0.08433322 0.06917735 0.78844254 0.69945304]]

 [[0.78987861 0.45346075 0.01783496 0.87006623 0.00520481]
  [0.49921883 0.56738806 0.1913215  0.42836827 0.8401404 ]
  [0.44430911 0.51624073 0.18058407 0.12971309 0.77588275]]]
[[[-1.7235828   0.40027189 -1.42442496 -0.17927749  0.11543661]
  [ 0.24829113 -1.18313967  1.40538404 -1.05655395  0.95074596]
  [ 0.30481548  0.



```
# This is formatted as code
```


### 4. Print a.


In [39]:
### [your code here]
import numpy as np

print("Array a:\n", a)



Array a:
 [[[30 94 74 70 56]
  [93 36 67 88 41]
  [67 33 50 83 50]]

 [[91 15 87 83  2]
  [ 8 71 80 59 33]
  [88 52 39 90 91]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [40]:
### [your code here]
import numpy as np

b = np.ones((5, 2, 3))

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [41]:
### [your code here]
import numpy as np
print("Array b:\n", b)


Array b:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [42]:
### [your code here]
# Check if 'a' and 'b' have the same size
import numpy as np

a = np.random.random((8, 4, 9))
b = np.ones((5, 15, 3))

# Check if sizes are the same
same_size = a.size == b.size

print("Size of a:", a.size)
print("Size of b:", b.size)
print("Do 'a' and 'b' have the same size?", same_size)


Size of a: 288
Size of b: 225
Do 'a' and 'b' have the same size? False



### 8. Are you able to add a and b? Why or why not?


In [43]:
### [your code here]
try:
    c = a + b
    print("Addition successful!")
    print(c)
except ValueError as e:
    print("Error:", e)


Error: operands could not be broadcast together with shapes (8,4,9) (5,15,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [44]:
### [your code here]
import numpy as np

a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))

c = b.transpose(1, 2, 0)

print("Array c (Transposed b):\n", c)

Array c (Transposed b):
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [45]:
### [your code here]
d = a + c

print("Array d (sum of a and c):\n", d)

Array d (sum of a and c):
 [[[1.41854323 1.88837047 1.79197603 1.53890355 1.95529626]
  [1.08978441 1.36974197 1.09148916 1.53155819 1.52170819]
  [1.79942871 1.63197885 1.65973256 1.17769137 1.03116896]]

 [[1.71858307 1.06593795 1.31221892 1.88194127 1.01249659]
  [1.57256212 1.51081406 1.1367094  1.12927702 1.05309469]
  [1.20327602 1.18881602 1.99673839 1.27322474 1.13392483]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [46]:
### [your code here]

print("Array a:\n", a)
print("\nArray d (sum of a and c):\n", d)

Array a:
 [[[0.41854323 0.88837047 0.79197603 0.53890355 0.95529626]
  [0.08978441 0.36974197 0.09148916 0.53155819 0.52170819]
  [0.79942871 0.63197885 0.65973256 0.17769137 0.03116896]]

 [[0.71858307 0.06593795 0.31221892 0.88194127 0.01249659]
  [0.57256212 0.51081406 0.1367094  0.12927702 0.05309469]
  [0.20327602 0.18881602 0.99673839 0.27322474 0.13392483]]]

Array d (sum of a and c):
 [[[1.41854323 1.88837047 1.79197603 1.53890355 1.95529626]
  [1.08978441 1.36974197 1.09148916 1.53155819 1.52170819]
  [1.79942871 1.63197885 1.65973256 1.17769137 1.03116896]]

 [[1.71858307 1.06593795 1.31221892 1.88194127 1.01249659]
  [1.57256212 1.51081406 1.1367094  1.12927702 1.05309469]
  [1.20327602 1.18881602 1.99673839 1.27322474 1.13392483]]]



### 12. Multiply a and c. Assign the result to e.


In [47]:
### [your code here]
e = a * c

print("Array e (product of a and c):\n", e)

Array e (product of a and c):
 [[[0.41854323 0.88837047 0.79197603 0.53890355 0.95529626]
  [0.08978441 0.36974197 0.09148916 0.53155819 0.52170819]
  [0.79942871 0.63197885 0.65973256 0.17769137 0.03116896]]

 [[0.71858307 0.06593795 0.31221892 0.88194127 0.01249659]
  [0.57256212 0.51081406 0.1367094  0.12927702 0.05309469]
  [0.20327602 0.18881602 0.99673839 0.27322474 0.13392483]]]




### 13. Does e equal to a? Why or why not?


In [48]:
### [your code here]
import numpy as np

a = np.array([[4, 16, 3], [8, 5, 6]])
e = np.array([[1, 2, 7], [81, 66, 14]])
d = np.array([[5, 2, 7], [7, 4, 0]])

e = a * d

#  if a and e are equal
print("a = \n", a)
print("\nMultiplication of a and d (e): \n", e)

print("\nIs e equal to a?", np.array_equal(a, e))

# e is not a copy of a, but a new matrix resulting from a different mathematical operation.

a = 
 [[ 4 16  3]
 [ 8  5  6]]

Multiplication of a and d (e): 
 [[20 32 21]
 [56 20  0]]

Is e equal to a? False




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [49]:
### [your code here]
import numpy as np

d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 7
Min value in d: 0
Mean value in d: 4.166666666666667



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [50]:
### [your code here]
import numpy as np

f = np.empty(d.shape)

print("Array f:")
print(f)

Array f:
[[4.94e-324 9.88e-324 3.46e-323]
 [4.00e-322 3.26e-322 6.92e-323]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [51]:
### [your code here]
d = [[3, 7, 9], [12, 15, 18], [5, 10, 20]]

flat_d = [value for row in d for value in row]  # Flatten the 2D list
d_min = min(flat_d)
d_max = max(flat_d)
d_mean = sum(flat_d) / len(flat_d)

f = []
for row in d:
    f_row = []
    for value in row:
        if value == d_min:
            f_row.append(0)
        elif d_min < value < d_mean:
            f_row.append(25)
        elif value == d_mean:
            f_row.append(50)
        elif d_mean < value < d_max:
            f_row.append(75)
        elif value == d_max:
            f_row.append(100)
    f.append(f_row)

print("Original d matrix:")
for row in d:
    print(row)

print("\nTransformed f matrix:")
for row in f:
    print(row)


Original d matrix:
[3, 7, 9]
[12, 15, 18]
[5, 10, 20]

Transformed f matrix:
[0, 25, 25]
[75, 75, 75]
[25, 25, 100]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [52]:
### [your code here]
import numpy as np

d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)

f = np.zeros_like(d)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_mean < value < d_max:
                f[i, j, k] = 75
            elif value == d_max:
                f[i, j, k] = 100

print("Original d array:\n", d)
print("\nTransformed f array:\n", f)

expected_f = np.array([[[ 75., 75., 75., 25., 75.],
                         [ 75., 75., 25., 25., 25.],
                         [ 75., 25., 75., 75., 75.]],

                        [[ 25.,  25.,  25.,  25., 100.],
                         [ 75.,  75.,  75.,  75.,  75.],
                         [ 25.,  75.,   0.,  75.,  75.]]])

print("\nDoes f match the expected output?", np.array_equal(f, expected_f))


Original d array:
 [[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]

Transformed f array:
 [[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]

Does f match the expected output? True


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [53]:
### [your code here]
import numpy as np

d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
f = np.empty(d.shape, dtype=object)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_mean:
                f[i, j, k] = "C"
            elif value == d_max:
                f[i, j, k] = "E"
            elif value == d_min:
                f[i, j, k] = "A"
            elif d_min < value < d_mean:
                f[i, j, k] = "B"
            elif d_mean < value < d_max:
                f[i, j, k] = "D"

print("d array:")
print(d)

print("\nf array:")
print(f)

d array:
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]

f array:
[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
